#!/usr/bin/env bash
# Save piped email to "$1/YYMMDD SUBJECT.eml"

# Don't overwrite existing file
set -o noclobber

echo "Fetching mail...."

message=$(cat)

# Just receive and exit if no folder name
if [[ "$1" == "" ]]
then
	exit
fi

mail_date=$(<<<"$message" grep -oPm 1 '^Date: ?\K.*')
formatted_date=$(date -d"$mail_date" +%y%m%d)
# Get the first line of the subject, and change / to ∕ so it's not a subdirectory
subject=$(<<<"$message" grep -oPm 1 '^Subject: ?\K.*' | sed 's,/,∕,g')
fsubject=${subject// /-}

if [[ $formatted_date == '' ]]; then
  echo Error: no date parsed
  exit 1
elif [[ $fsubject == '' ]]; then
  echo Warning: no subject found
fi

mkdir -p $1
echo "${message}" > "$1/$fsubject.eml" && echo Email saved to "$1/$fsubject.eml"
